export const FREE_PLAN_LIMITS = {
  MAX_PLANEJAMENTOS: 4,
  IA_REPORTS_PER_MONTH: 3,
  GEMINI_CALLS_PER_HOUR: 10,
  PHOTO_UPLOADS_PER_HOUR: 20,
  LOGIN_ATTEMPTS_PER_IP_HOUR: 10,
} as const;

export const PRO_PLAN_LIMITS = {
  IA_REPORTS_PER_MONTH: 30,
  GEMINI_CALLS_PER_HOUR: 50,
  PHOTO_UPLOADS_PER_HOUR: 20,
} as const;

export const SIGNED_URL_TTL_SECONDS = 60 * 60;
export const MAX_PHOTO_SIZE_BYTES = 10 * 1024 * 1024;
