type CatalogActivity = {
  titulo: string;
  descricao: string;
  categoria: string;
  duracao: number;
  materiais: string[];
  bnccCodigos: string[];
};

type CatalogProject = {
  titulo: string;
  descricao: string;
  categoria: string;
  faixaEtaria: string;
  duracao: string;
  bnccObjetivos: string[];
  premium: boolean;
  atividades: CatalogActivity[];
};

export const PROJECT_CATALOG: CatalogProject[] = [
  {
    titulo: "Descobertas Sensoriais do Bercario",
    descricao: "Sequencia de exploracoes sensoriais com foco em vinculo, cuidado e descoberta dos sentidos.",
    categoria: "Natureza",
    faixaEtaria: "Bercario",
    duracao: "2 semanas",
    bnccObjetivos: [
      "Explorar sons, texturas e movimentos com seguranca",
      "Fortalecer vinculo afetivo por meio de interacoes mediadas",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Tapete sensorial de tecidos",
        descricao: "Percurso com tecidos de diferentes texturas para toque com maos e pes.",
        categoria: "Sensorial",
        duracao: 20,
        materiais: ["feltro", "algodao", "EVA", "tapete antiderrapante"],
        bnccCodigos: ["EI01EO01", "EI01CG02"],
      },
      {
        titulo: "Cesta do tesouro natural",
        descricao: "Exploracao supervisionada de elementos seguros da natureza.",
        categoria: "Natureza",
        duracao: 25,
        materiais: ["pinhas", "sementes grandes", "folhas secas"],
        bnccCodigos: ["EI01ET01"],
      },
      {
        titulo: "Musica calma e gestos",
        descricao: "Roda com cancoes e repeticao de gestos simples de imitar.",
        categoria: "Linguagem",
        duracao: 15,
        materiais: ["caixa de som", "chocalhos"],
        bnccCodigos: ["EI01EF01"],
      },
    ],
  },
  {
    titulo: "Ritmos e Vinculos no Bercario",
    descricao: "Projeto de musicalizacao inicial com movimento corporal, escuta e rotina afetiva.",
    categoria: "Arte",
    faixaEtaria: "Bercario",
    duracao: "3 semanas",
    bnccObjetivos: [
      "Perceber ritmos, pausas e sons do ambiente",
      "Participar de experiencias musicais em grupo",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Chocalho do nome",
        descricao: "Cada crianca reage ao proprio nome com som e acolhimento.",
        categoria: "Musicalizacao",
        duracao: 15,
        materiais: ["chocalhos", "tapete", "cartoes com nomes"],
        bnccCodigos: ["EI01EF02"],
      },
      {
        titulo: "Cantinho de sons da sala",
        descricao: "Exploracao de sons cotidianos com mediação da professora.",
        categoria: "Natureza",
        duracao: 20,
        materiais: ["potes", "colheres de madeira", "papel"],
        bnccCodigos: ["EI01ET03"],
      },
      {
        titulo: "Danca com tecidos leves",
        descricao: "Movimentos amplos com tecidos coloridos ao som de musica lenta.",
        categoria: "Corpo",
        duracao: 20,
        materiais: ["tecidos leves", "caixa de som"],
        bnccCodigos: ["EI01CG03"],
      },
    ],
  },
  {
    titulo: "Maternal Investigador do Quintal",
    descricao: "Vivencias de investigacao do ambiente externo com registros simples e rodas de conversa.",
    categoria: "Natureza",
    faixaEtaria: "Maternal",
    duracao: "4 semanas",
    bnccObjetivos: [
      "Observar transformacoes no ambiente",
      "Ampliar vocabulario em contextos reais",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Caca as cores do jardim",
        descricao: "Busca guiada por elementos naturais por cor.",
        categoria: "Natureza",
        duracao: 30,
        materiais: ["cestos", "cartoes de cor"],
        bnccCodigos: ["EI02ET02"],
      },
      {
        titulo: "Registro com colagem",
        descricao: "Montagem de painel com folhas e sementes coletadas.",
        categoria: "Arte",
        duracao: 35,
        materiais: ["cartolina", "cola", "elementos coletados"],
        bnccCodigos: ["EI02TS01"],
      },
      {
        titulo: "Roda de descobertas",
        descricao: "Relato oral das descobertas com mediação de perguntas.",
        categoria: "Linguagem",
        duracao: 25,
        materiais: ["objetos coletados"],
        bnccCodigos: ["EI02EF01"],
      },
      {
        titulo: "Mini horta da turma",
        descricao: "Plantio de ervas em pequenos vasos com rotina de cuidados.",
        categoria: "Natureza",
        duracao: 40,
        materiais: ["vasos", "terra", "sementes"],
        bnccCodigos: ["EI02ET03"],
      },
    ],
  },
  {
    titulo: "Primeiras Narrativas do Maternal",
    descricao: "Projeto de linguagem oral e escuta ativa com contacao, reconto e dramatizacao.",
    categoria: "Linguagem",
    faixaEtaria: "Maternal",
    duracao: "3 semanas",
    bnccObjetivos: [
      "Escutar e reconto de historias com apoio visual",
      "Participar de situacoes comunicativas em grupo",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Caixa surpresa de personagens",
        descricao: "Abertura de caixa com elementos da historia do dia.",
        categoria: "Linguagem",
        duracao: 20,
        materiais: ["caixa", "fantoches", "figuras"],
        bnccCodigos: ["EI02EF02"],
      },
      {
        titulo: "Sequencia de cenas",
        descricao: "Ordenacao de imagens para contar inicio, meio e fim.",
        categoria: "Linguagem",
        duracao: 30,
        materiais: ["cartoes ilustrados"],
        bnccCodigos: ["EI02EF03"],
      },
      {
        titulo: "Teatrinho de repeticao",
        descricao: "Representacao curta com frases repetidas da historia.",
        categoria: "Arte",
        duracao: 30,
        materiais: ["fantasias", "fantoches"],
        bnccCodigos: ["EI02TS03"],
      },
    ],
  },
  {
    titulo: "Movimento e Equilibrio no Maternal",
    descricao: "Circuitos motores para coordenacao ampla, equilibrio e cooperacao.",
    categoria: "Corpo",
    faixaEtaria: "Maternal",
    duracao: "3 semanas",
    bnccObjetivos: [
      "Ampliar repertorio motor em percursos variados",
      "Desenvolver autonomia corporal em brincadeiras",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Circuito de almofadas",
        descricao: "Percurso com desafios de subir, descer e contornar obstaculos.",
        categoria: "Corpo",
        duracao: 30,
        materiais: ["almofadas", "cones", "arcos"],
        bnccCodigos: ["EI02CG02"],
      },
      {
        titulo: "Corrida dos animais",
        descricao: "Movimentacao imitando animais em diferentes velocidades.",
        categoria: "Corpo",
        duracao: 25,
        materiais: ["cartoes de animais"],
        bnccCodigos: ["EI02CG03"],
      },
      {
        titulo: "Relaxamento guiado",
        descricao: "Fechamento da atividade com respiracao e alongamentos simples.",
        categoria: "Bem-estar",
        duracao: 15,
        materiais: ["colchonetes", "musica calma"],
        bnccCodigos: ["EI02EO04"],
      },
    ],
  },
  {
    titulo: "Jardim dos Pequenos Cientistas",
    descricao: "Experimentos de ciencias para explorar hipoteses, observacao e registro coletivo.",
    categoria: "Natureza",
    faixaEtaria: "Jardim",
    duracao: "4 semanas",
    bnccObjetivos: [
      "Elaborar hipoteses sobre fenomenos simples",
      "Registrar descobertas com diferentes linguagens",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Mistura que muda de cor",
        descricao: "Experimento com indicadores naturais e comparacao de resultados.",
        categoria: "Natureza",
        duracao: 40,
        materiais: ["repolho roxo", "copos", "vinagre", "bicarbonato"],
        bnccCodigos: ["EI03ET02"],
      },
      {
        titulo: "Roda de hipoteses",
        descricao: "As criancas antecipam resultados antes de experimentar.",
        categoria: "Linguagem",
        duracao: 25,
        materiais: ["quadro", "marcadores"],
        bnccCodigos: ["EI03EF01"],
      },
      {
        titulo: "Diario ilustrado",
        descricao: "Registro em desenho e legenda de cada experimento.",
        categoria: "Arte",
        duracao: 35,
        materiais: ["caderno", "lapis de cor"],
        bnccCodigos: ["EI03TS02"],
      },
      {
        titulo: "Mostra cientifica da turma",
        descricao: "Apresentacao das descobertas para outra turma.",
        categoria: "Social",
        duracao: 45,
        materiais: ["cartazes", "mesa de exposicao"],
        bnccCodigos: ["EI03EO03"],
      },
    ],
  },
  {
    titulo: "Matematica do Cotidiano no Jardim",
    descricao: "Situacoes-problema com contagem, comparacao e organizacao de dados simples.",
    categoria: "Matematica",
    faixaEtaria: "Jardim",
    duracao: "3 semanas",
    bnccObjetivos: [
      "Reconhecer quantidades em contextos reais",
      "Comparar grandezas e registrar resultados",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Mercadinho da turma",
        descricao: "Brincadeira de compra e venda com contagem de itens.",
        categoria: "Matematica",
        duracao: 35,
        materiais: ["embalagens", "fichas numericas"],
        bnccCodigos: ["EI03ET07"],
      },
      {
        titulo: "Grafico do lanche",
        descricao: "Registro de preferencia alimentar em grafico de colunas.",
        categoria: "Matematica",
        duracao: 30,
        materiais: ["adesivos", "cartaz"],
        bnccCodigos: ["EI03ET05"],
      },
      {
        titulo: "Desafio dos blocos",
        descricao: "Construcoes com limite de pecas para resolver desafios.",
        categoria: "Corpo",
        duracao: 25,
        materiais: ["blocos", "cartoes de desafio"],
        bnccCodigos: ["EI03CG02"],
      },
    ],
  },
  {
    titulo: "Atelie Criativo do Jardim",
    descricao: "Percurso artistico com diferentes suportes, tecnicas e apreciacao coletiva.",
    categoria: "Arte",
    faixaEtaria: "Jardim",
    duracao: "4 semanas",
    bnccObjetivos: [
      "Experimentar tecnicas artisticas variadas",
      "Compartilhar processos e producoes com o grupo",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Pintura com elementos naturais",
        descricao: "Uso de folhas e galhos para criar texturas de pintura.",
        categoria: "Arte",
        duracao: 40,
        materiais: ["tinta", "folhas", "galhos", "papel kraft"],
        bnccCodigos: ["EI03TS01"],
      },
      {
        titulo: "Escultura com reciclaveis",
        descricao: "Montagem de esculturas com material reutilizado.",
        categoria: "Criatividade",
        duracao: 45,
        materiais: ["caixas", "fitas", "cola", "rolos"],
        bnccCodigos: ["EI03TS02"],
      },
      {
        titulo: "Galeria da turma",
        descricao: "Curadoria e exposicao das producoes para as familias.",
        categoria: "Social",
        duracao: 35,
        materiais: ["painel", "pregadores", "etiquetas"],
        bnccCodigos: ["EI03EO05"],
      },
    ],
  },
  {
    titulo: "Laboratorio de Escrita da Pre-escola",
    descricao: "Projeto para ampliar repertorio de leitura e escrita emergente com intencionalidade.",
    categoria: "Linguagem",
    faixaEtaria: "Pre-escola",
    duracao: "5 semanas",
    bnccObjetivos: [
      "Reconhecer relacao entre fala e escrita",
      "Produzir textos coletivos com apoio da professora",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Bilhete para as familias",
        descricao: "Producoes coletivas com registro de recados da turma.",
        categoria: "Linguagem",
        duracao: 35,
        materiais: ["papel", "envelopes", "canetinhas"],
        bnccCodigos: ["EI03EF04"],
      },
      {
        titulo: "Oficina do nome completo",
        descricao: "Atividades de escrita do nome e sobrenome em suportes diversos.",
        categoria: "Linguagem",
        duracao: 30,
        materiais: ["fichas", "massinha", "quadro branco"],
        bnccCodigos: ["EI03EF03"],
      },
      {
        titulo: "Jornal da sala",
        descricao: "Organizacao de noticias da semana em painel colaborativo.",
        categoria: "Linguagem",
        duracao: 40,
        materiais: ["cartolina", "fotos", "legendas"],
        bnccCodigos: ["EI03EF05"],
      },
      {
        titulo: "Sarau de leitura",
        descricao: "Leitura compartilhada com convidadas da escola.",
        categoria: "Social",
        duracao: 35,
        materiais: ["livros", "microfone brinquedo"],
        bnccCodigos: ["EI03EO06"],
      },
    ],
  },
  {
    titulo: "Feira de Ciencias da Pre-escola",
    descricao: "Percurso investigativo com experimentos, registro e apresentacao final para comunidade.",
    categoria: "Natureza",
    faixaEtaria: "Pre-escola",
    duracao: "5 semanas",
    bnccObjetivos: [
      "Investigar fenomenos naturais com metodologia simples",
      "Comunicar descobertas para diferentes interlocutores",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Desafio da germinacao",
        descricao: "Comparacao de crescimento em diferentes condicoes de luz.",
        categoria: "Natureza",
        duracao: 45,
        materiais: ["sementes", "vasos", "regador"],
        bnccCodigos: ["EI03ET03"],
      },
      {
        titulo: "Registro em tabela",
        descricao: "Montagem de tabela semanal com medidas e observacoes.",
        categoria: "Matematica",
        duracao: 30,
        materiais: ["planilha impressa", "regua"],
        bnccCodigos: ["EI03ET08"],
      },
      {
        titulo: "Treino de apresentacao",
        descricao: "Ensaios para apresentar experimento para outras turmas.",
        categoria: "Linguagem",
        duracao: 30,
        materiais: ["cartazes", "marcadores"],
        bnccCodigos: ["EI03EF01"],
      },
    ],
  },
  {
    titulo: "Nossa Cidade e Comunidade",
    descricao: "Projeto de identidade e pertencimento com foco em espacos, servicos e cidadania.",
    categoria: "Sociedade",
    faixaEtaria: "Pre-escola",
    duracao: "4 semanas",
    bnccObjetivos: [
      "Compreender papeis sociais no territorio",
      "Valorizar diferentes formas de participacao comunitaria",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Mapa afetivo do bairro",
        descricao: "Representacao coletiva de locais significativos para as criancas.",
        categoria: "Sociedade",
        duracao: 40,
        materiais: ["papel metro", "adesivos", "canetas"],
        bnccCodigos: ["EI03EO03"],
      },
      {
        titulo: "Entrevista com funcionarias",
        descricao: "Roteiro e entrevista com profissionais da escola.",
        categoria: "Linguagem",
        duracao: 35,
        materiais: ["gravador", "caderno"],
        bnccCodigos: ["EI03EF02"],
      },
      {
        titulo: "Maquete da comunidade",
        descricao: "Construcao colaborativa da cidade com caixas e sucatas.",
        categoria: "Arte",
        duracao: 50,
        materiais: ["sucata", "cola", "tinta"],
        bnccCodigos: ["EI03TS02"],
      },
    ],
  },
  {
    titulo: "Horta Pedagogica Integrada",
    descricao: "Projeto continuo de cuidado com plantas, alimentacao e responsabilidade coletiva.",
    categoria: "Natureza",
    faixaEtaria: "Maternal e Jardim",
    duracao: "6 semanas",
    bnccObjetivos: [
      "Participar do cuidado com o ambiente",
      "Registrar processos de crescimento e colheita",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Preparacao dos canteiros",
        descricao: "Organizacao do espaco da horta com divisao de tarefas.",
        categoria: "Natureza",
        duracao: 45,
        materiais: ["terra", "pa infantil", "regador"],
        bnccCodigos: ["EI02ET03", "EI03ET03"],
      },
      {
        titulo: "Agenda de cuidados",
        descricao: "Definicao de rotina de rega e observacao por grupo.",
        categoria: "Matematica",
        duracao: 30,
        materiais: ["calendario", "adesivos"],
        bnccCodigos: ["EI03ET05"],
      },
      {
        titulo: "Receita da colheita",
        descricao: "Culinaria com vegetais colhidos e registro da receita.",
        categoria: "Linguagem",
        duracao: 50,
        materiais: ["ingredientes", "ficha de receita"],
        bnccCodigos: ["EI03EF04"],
      },
    ],
  },
  {
    titulo: "Brincadeiras do Brasil",
    descricao: "Resgate de brincadeiras tradicionais para desenvolver corpo, cultura e interacao.",
    categoria: "Corpo",
    faixaEtaria: "Jardim e Pre-escola",
    duracao: "3 semanas",
    bnccObjetivos: [
      "Vivenciar brincadeiras de diferentes contextos culturais",
      "Fortalecer cooperacao e combinados de grupo",
    ],
    premium: false,
    atividades: [
      {
        titulo: "Circuito de amarelinha",
        descricao: "Variacoes de amarelinha com desafios numericos.",
        categoria: "Corpo",
        duracao: 30,
        materiais: ["giz", "pedrinhas"],
        bnccCodigos: ["EI03CG02", "EI03ET07"],
      },
      {
        titulo: "Cantigas com roda",
        descricao: "Cantigas tradicionais com movimentos coletivos.",
        categoria: "Arte",
        duracao: 25,
        materiais: ["caixa de som"],
        bnccCodigos: ["EI03TS03"],
      },
      {
        titulo: "Livro das brincadeiras",
        descricao: "Registro ilustrado das brincadeiras preferidas da turma.",
        categoria: "Linguagem",
        duracao: 35,
        materiais: ["papel", "lapis", "grampeador"],
        bnccCodigos: ["EI03EF05"],
      },
    ],
  },
];
