import { getProjectCoverKey, type ProjectCoverKey } from "@/lib/project-cover";

export type ProjectCatalogItem = {
  titulo: string;
  descricao: string;
  categoria: string;
  faixaEtaria: string;
  duracao: string;
  coverKey: ProjectCoverKey;
  bnccObjetivos: string[];
  problema: string;
  justificativa: string;
  objetivoGeral: string;
  objetivosEspecificos: string[];
  camposExperiencia: string[];
  metodologia: string[];
  cronograma: string;
  avaliacao: string[];
  atividades: Array<{
    titulo: string;
    descricao: string;
    categoria: string;
    duracao: number;
    materiais: string[];
    bnccCodigos: string[];
  }>;
};

type ProjectBlueprint = {
  titulo: string;
  descricao: string;
  categoria: string;
  faixaEtaria: string;
  duracao: string;
  objetivos: [string, string, string];
  atividades: [string, string, string, string, string];
  materiais: [string, string, string, string, string, string];
  codigos: [string, string, string, string];
};

const ACTIVITY_DESCRIPTIONS = [
  "Roda curta para levantar repertórios, combinar cuidados e registrar hipóteses da turma.",
  "Vivência prática em pequenos grupos, com mediação da professora e exploração livre dos materiais.",
  "Produção coletiva ou individual para transformar descobertas em uma criação visível.",
  "Registro com desenhos, fotos, listas, marcas gráficas ou relato oral organizado pela professora.",
  "Socialização final para retomar aprendizagens, organizar materiais e envolver famílias ou outras turmas.",
] as const;

const CAMPOS_BNCC = {
  EO: "O eu, o outro e o nos: convivencia, autonomia, identidade, respeito e cooperacao.",
  CG: "Corpo, gestos e movimentos: movimentos amplos, coordenacao, cuidado e expressao corporal.",
  TS: "Tracos, sons, cores e formas: producao artistica, exploracao de materiais, sons, cores e imagens.",
  EF: "Escuta, fala, pensamento e imaginacao: oralidade, narrativas, leitura, registros e comunicacao.",
  ET: "Espacos, tempos, quantidades, relacoes e transformacoes: investigacao, comparacao, medidas e natureza.",
} as const;

const DEFAULT_AVALIACAO = [
  "Participa das propostas com interesse, curiosidade e envolvimento progressivo.",
  "Manipula e explora materiais variados, demonstrando descobertas por gestos, fala, desenho ou movimento.",
  "Interage com colegas e adultos, respeitando combinados e ampliando atitudes de cooperacao.",
  "Reconhece imagens, sons, cores, formas, texturas ou elementos relacionados ao tema.",
  "Relata experiencias, formula hipoteses e comunica preferencias conforme sua faixa etaria.",
  "Demonstra avancos em autonomia, coordenacao motora, linguagem e participacao nas atividades.",
];

function rotate<T>(items: readonly T[], start: number, size: number) {
  return Array.from({ length: size }, (_, index) => items[(start + index) % items.length]);
}

function camposExperienciaFromCodigos(codigos: readonly string[]) {
  const keys = new Set(
    codigos
      .map((codigo) => codigo.match(/EI\d{2}([A-Z]{2})/)?.[1])
      .filter((key): key is keyof typeof CAMPOS_BNCC => Boolean(key && key in CAMPOS_BNCC)),
  );

  const campos = Array.from(keys).map((key) => CAMPOS_BNCC[key]);
  return campos.length ? campos : Object.values(CAMPOS_BNCC);
}

function buildProject(blueprint: ProjectBlueprint): ProjectCatalogItem {
  const atividades = blueprint.atividades.map((titulo, index) => ({
    titulo,
    descricao: ACTIVITY_DESCRIPTIONS[index],
    categoria: blueprint.categoria,
    duracao: 20 + index * 5,
    materiais: rotate(blueprint.materiais, index, 4),
    bnccCodigos: rotate(blueprint.codigos, index, 2),
  }));
  const metodologia = atividades.map((atividade) => `${atividade.titulo}: ${atividade.descricao}`);
  const codigos = atividades.flatMap((atividade) => atividade.bnccCodigos).concat(blueprint.codigos);

  return {
    titulo: blueprint.titulo,
    descricao: blueprint.descricao,
    categoria: blueprint.categoria,
    faixaEtaria: blueprint.faixaEtaria,
    duracao: blueprint.duracao,
    coverKey: getProjectCoverKey(blueprint.titulo, blueprint.categoria),
    bnccObjetivos: blueprint.objetivos,
    problema: `Que perguntas, descobertas e experiencias as criancas podem construir a partir do tema ${blueprint.titulo}?`,
    justificativa: `O projeto nasce do interesse das criancas por experiencias significativas ligadas a ${blueprint.categoria.toLowerCase()}. Considerando a faixa etaria ${blueprint.faixaEtaria}, a proposta organiza situacoes de brincadeira, investigacao, expressao e convivencia para ampliar repertorios e fortalecer aprendizagens. Ao longo do percurso, a turma participa de rodas de conversa, exploracoes com materiais, registros, producoes e socializacoes, favorecendo vinculos, autonomia, linguagem e observacao do mundo. A parceria com as familias e o uso de materiais simples tornam o projeto acessivel, contextualizado e adequado a diferentes realidades escolares.`,
    objetivoGeral: `Proporcionar experiencias integradas sobre ${blueprint.titulo}, favorecendo curiosidade, participacao, convivencia, expressao e desenvolvimento integral das criancas.`,
    objetivosEspecificos: [
      ...blueprint.objetivos,
      "Participar de rodas de conversa, brincadeiras e producoes individuais ou coletivas.",
      "Explorar materiais, imagens, sons, movimentos e registros relacionados ao tema.",
      "Comunicar descobertas por meio da fala, gestos, desenho, musica, movimento ou faz de conta.",
    ],
    camposExperiencia: camposExperienciaFromCodigos(codigos),
    metodologia,
    cronograma: blueprint.duracao,
    avaliacao: DEFAULT_AVALIACAO,
    atividades,
  };
}

const PROJECT_BLUEPRINTS: ProjectBlueprint[] = [
  {
    titulo: "Descobertas Sensoriais do Bercário",
    descricao: "Percurso de exploração tátil, sonora e visual para ampliar vínculo, curiosidade e segurança corporal.",
    categoria: "Natureza",
    faixaEtaria: "Berçário (0-1 ano)",
    duracao: "2 semanas",
    objetivos: ["Explorar diferentes texturas com segurança.", "Responder a sons, gestos e expressões da professora.", "Ampliar vínculos em situações de cuidado e brincadeira."],
    atividades: ["Tapete sensorial de tecidos", "Cesta do tesouro natural", "Sons suaves e gestos", "Marcas com tinta comestível", "Varal das descobertas"],
    materiais: ["tecidos", "esponjas", "folhas grandes", "chocalhos", "tinta comestível", "papel kraft"],
    codigos: ["EI01EO01", "EI01CG02", "EI01TS01", "EI01ET03"],
  },
  {
    titulo: "Ritmos e Vínculos no Bercário",
    descricao: "Sequência musical com canções, pulso e objetos sonoros para fortalecer atenção compartilhada.",
    categoria: "Música",
    faixaEtaria: "Berçário (0-1 ano)",
    duracao: "2 semanas",
    objetivos: ["Reconhecer ritmos simples na rotina.", "Participar de brincadeiras cantadas.", "Expressar preferências por sons e movimentos."],
    atividades: ["Chocalho do nome", "Canções de colo", "Pausa e movimento", "Exploração de tambores macios", "Concerto para a sala"],
    materiais: ["chocalhos", "potes plásticos", "tecidos", "caixa de som", "almofadas", "fitas coloridas"],
    codigos: ["EI01TS03", "EI01EO02", "EI01CG03", "EI01EF01"],
  },
  {
    titulo: "Luzes e Sombras para Bebês",
    descricao: "Investigação visual com contrastes, lanternas e sombras em ambiente acolhedor.",
    categoria: "Arte",
    faixaEtaria: "Berçário (0-1 ano)",
    duracao: "2 semanas",
    objetivos: ["Observar contrastes de luz e sombra.", "Acompanhar movimentos com o olhar.", "Explorar objetos translúcidos com curiosidade."],
    atividades: ["Cantinho escuro seguro", "Dança das sombras", "Garrafas de luz", "Painel translúcido", "Mostra de contrastes"],
    materiais: ["lanternas", "papel celofane", "garrafas PET", "tecidos claros", "cartolina preta", "fita adesiva"],
    codigos: ["EI01TS02", "EI01ET02", "EI01CG01", "EI01EO03"],
  },
  {
    titulo: "Cestos de Tesouros Naturais",
    descricao: "Coleção de objetos naturais para exploração acompanhada, classificação inicial e linguagem afetiva.",
    categoria: "Natureza",
    faixaEtaria: "Berçário (1-2 anos)",
    duracao: "3 semanas",
    objetivos: ["Manipular objetos naturais com cuidado.", "Perceber diferenças de peso, forma e textura.", "Nomear sensações com apoio adulto."],
    atividades: ["Cesto de folhas e sementes", "Objetos leves e pesados", "Cheiros do quintal", "Classificação por textura", "Museu dos tesouros"],
    materiais: ["cestos", "folhas", "sementes grandes", "pedras lisas", "ervas aromáticas", "tecidos"],
    codigos: ["EI01ET03", "EI01EO04", "EI01CG05", "EI01EF02"],
  },
  {
    titulo: "Corpo que Explora",
    descricao: "Percurso motor de rolar, engatinhar, subir e descer com segurança e intencionalidade.",
    categoria: "Corpo",
    faixaEtaria: "Berçário (1-2 anos)",
    duracao: "3 semanas",
    objetivos: ["Experimentar deslocamentos variados.", "Construir confiança em desafios motores.", "Perceber limites do próprio corpo."],
    atividades: ["Túnel de tecidos", "Rampas de espuma", "Caminho de almofadas", "Bolas grandes", "Mapa corporal da turma"],
    materiais: ["almofadas", "colchonetes", "túnel", "bolas", "fitas", "espelhos"],
    codigos: ["EI01CG02", "EI01CG03", "EI01EO02", "EI01ET04"],
  },
  {
    titulo: "Histórias de Colo",
    descricao: "Rotina literária com livros resistentes, fantoches e reconto por gestos.",
    categoria: "Linguagem",
    faixaEtaria: "Berçário (1-2 anos)",
    duracao: "2 semanas",
    objetivos: ["Apreciar livros e imagens.", "Responder a personagens com gestos e sons.", "Ampliar repertório de palavras da rotina."],
    atividades: ["Livro surpresa", "Fantoche visitante", "Som dos personagens", "Cesto de imagens", "Reconto com famílias"],
    materiais: ["livros cartonados", "fantoches", "figuras plastificadas", "tapete", "caixa surpresa", "tecidos"],
    codigos: ["EI01EF03", "EI01EF04", "EI01EO01", "EI01TS01"],
  },
  {
    titulo: "Água e Texturas",
    descricao: "Exploração de água, gelo, esponjas e recipientes para observar transformações simples.",
    categoria: "Natureza",
    faixaEtaria: "Berçário (1-2 anos)",
    duracao: "2 semanas",
    objetivos: ["Explorar água em diferentes estados.", "Experimentar ações de encher, apertar e transferir.", "Construir atitudes de cuidado durante a brincadeira."],
    atividades: ["Bacia de esponjas", "Gelo colorido seguro", "Transferência com potes", "Marcas molhadas", "Roda do cuidado"],
    materiais: ["bacias", "esponjas", "potes", "gelo", "corante alimentício", "toalhas"],
    codigos: ["EI01ET02", "EI01CG05", "EI01EO03", "EI01TS02"],
  },
  {
    titulo: "Sons da Natureza",
    descricao: "Escuta ativa de chuva, vento, folhas e animais com criação de paisagens sonoras.",
    categoria: "Música",
    faixaEtaria: "Berçário (1-2 anos)",
    duracao: "3 semanas",
    objetivos: ["Diferenciar sons naturais.", "Imitar sons com corpo e objetos.", "Participar de uma paisagem sonora coletiva."],
    atividades: ["Escuta do quintal", "Folhas que fazem som", "Chuva no pote", "Vento com tecidos", "Paisagem sonora"],
    materiais: ["folhas secas", "potes", "sementes", "tecidos", "caixa de som", "cartazes"],
    codigos: ["EI01TS03", "EI01ET03", "EI01EF01", "EI01EO04"],
  },
  {
    titulo: "Pequenos Cuidados",
    descricao: "Projeto de autonomia em alimentação, higiene e organização por meio de brincadeiras simbólicas.",
    categoria: "Bem-estar",
    faixaEtaria: "Berçário (1-2 anos)",
    duracao: "3 semanas",
    objetivos: ["Participar de cuidados cotidianos.", "Reconhecer objetos de higiene e alimentação.", "Praticar pequenas escolhas com apoio adulto."],
    atividades: ["Bonecos no banho", "Mesa de faz de conta", "Guardar e encontrar", "Fotos da rotina", "Combinados visuais"],
    materiais: ["bonecos", "bacias", "paninhos", "colheres", "fotos da rotina", "cestos"],
    codigos: ["EI01EO05", "EI01CG04", "EI01EF02", "EI01ET06"],
  },
  {
    titulo: "Tapetes de Percurso",
    descricao: "Circuitos sensoriais no chão para investigar caminhos, direções e equilíbrio.",
    categoria: "Corpo",
    faixaEtaria: "Berçário (1-2 anos)",
    duracao: "2 semanas",
    objetivos: ["Explorar caminhos com pés e mãos.", "Perceber diferenças de superfície.", "Experimentar equilíbrio com segurança."],
    atividades: ["Caminho macio", "Pés que sentem", "Trilha com fitas", "Circuito com obstáculos", "Registro das pegadas"],
    materiais: ["tapetes", "EVA", "fitas", "almofadas", "tinta lavável", "papel kraft"],
    codigos: ["EI01CG02", "EI01CG05", "EI01ET04", "EI01TS02"],
  },
  {
    titulo: "Cheiros e Sabores Seguros",
    descricao: "Investigação supervisionada com alimentos e aromas da rotina para ampliar linguagem sensorial.",
    categoria: "Natureza",
    faixaEtaria: "Berçário (1-2 anos)",
    duracao: "2 semanas",
    objetivos: ["Perceber aromas e sabores familiares.", "Expressar preferências por gestos e palavras.", "Relacionar alimentos aos cuidados da rotina."],
    atividades: ["Potes de aromas", "Frutas da estação", "Carimbo com legumes", "Livro dos sabores", "Piquenique da turma"],
    materiais: ["frutas", "ervas", "potes", "legumes", "papel", "tinta comestível"],
    codigos: ["EI01ET03", "EI01EF02", "EI01EO04", "EI01CG04"],
  },
  {
    titulo: "Brincar com Tecidos",
    descricao: "Exploração de tecidos para esconder, revelar, balançar e criar vínculos.",
    categoria: "Arte",
    faixaEtaria: "Berçário (1-2 anos)",
    duracao: "2 semanas",
    objetivos: ["Criar gestos com tecidos.", "Participar de jogos de esconder e aparecer.", "Explorar cores, transparências e movimento."],
    atividades: ["Cadê, achou", "Dança dos lenços", "Casinha de tecido", "Painel de transparências", "Cortejo colorido"],
    materiais: ["lenços", "tecidos leves", "varal", "prendedores", "bambolês", "música"],
    codigos: ["EI01TS02", "EI01CG03", "EI01EO02", "EI01EF01"],
  },
  {
    titulo: "Maternal Investigador do Quintal",
    descricao: "Percurso de observação do quintal com coleta, comparação e registros simples.",
    categoria: "Natureza",
    faixaEtaria: "Maternal I (2-3 anos)",
    duracao: "3 semanas",
    objetivos: ["Observar elementos naturais do entorno.", "Comparar cores, tamanhos e texturas.", "Registrar descobertas por colagem e fala."],
    atividades: ["Caça às cores do jardim", "Bandeja de achados", "Colagem das descobertas", "Roda de hipóteses", "Mini exposição"],
    materiais: ["pranchetas", "folhas", "gravetos", "cola", "cartolina", "lupas"],
    codigos: ["EI02ET02", "EI02EF01", "EI02TS02", "EI02EO04"],
  },
  {
    titulo: "Primeiras Narrativas do Maternal",
    descricao: "Sequência de oralidade com cenas, objetos e personagens para organizar começo, meio e fim.",
    categoria: "Linguagem",
    faixaEtaria: "Maternal I (2-3 anos)",
    duracao: "3 semanas",
    objetivos: ["Contar acontecimentos com apoio visual.", "Participar de reconto coletivo.", "Ampliar repertório de personagens e ações."],
    atividades: ["Caixa surpresa de personagens", "Sequência de cenas", "Teatro de repetição", "Livro coletivo", "Roda de reconto"],
    materiais: ["fantoches", "cartões de cena", "caixa", "papel", "canetões", "livros"],
    codigos: ["EI02EF03", "EI02EF04", "EI02EO03", "EI02TS03"],
  },
  {
    titulo: "Movimento e Equilíbrio no Maternal",
    descricao: "Circuito motor progressivo com desafios de saltar, passar por baixo e equilibrar objetos.",
    categoria: "Corpo",
    faixaEtaria: "Maternal I (2-3 anos)",
    duracao: "3 semanas",
    objetivos: ["Experimentar movimentos amplos.", "Respeitar turnos em circuito.", "Nomear partes do corpo em ação."],
    atividades: ["Circuito de almofadas", "Corrida dos animais", "Linha do equilíbrio", "Bola ao alvo", "Relaxamento guiado"],
    materiais: ["almofadas", "cones", "bolas", "corda", "arcos", "colchonetes"],
    codigos: ["EI02CG02", "EI02CG03", "EI02EO06", "EI02EF01"],
  },
  {
    titulo: "Cores da Natureza",
    descricao: "Pesquisa de pigmentos naturais, mistura de cores e produção de painel coletivo.",
    categoria: "Arte",
    faixaEtaria: "Maternal I (2-3 anos)",
    duracao: "3 semanas",
    objetivos: ["Investigar cores presentes em elementos naturais.", "Experimentar misturas e marcas.", "Produzir composição coletiva."],
    atividades: ["Coleta colorida", "Tinta de terra e folhas", "Carimbos naturais", "Painel de cores", "Galeria da turma"],
    materiais: ["terra", "folhas", "beterraba", "papel kraft", "pincéis grossos", "aventais"],
    codigos: ["EI02TS02", "EI02ET02", "EI02CG05", "EI02EF01"],
  },
  {
    titulo: "Mini Horta do Maternal",
    descricao: "Plantio em vasos, cuidados diários e observação de crescimento com registros visuais.",
    categoria: "Natureza",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "5 semanas",
    objetivos: ["Participar do cuidado com plantas.", "Observar mudanças ao longo do tempo.", "Relacionar plantio, água e luz."],
    atividades: ["Preparar os vasos", "Plantar sementes", "Agenda de rega", "Desenho do crescimento", "Colheita simbólica"],
    materiais: ["vasos", "terra", "sementes", "regadores", "palitos", "cartolina"],
    codigos: ["EI02ET03", "EI02EO01", "EI02EF05", "EI02TS02"],
  },
  {
    titulo: "Mercado de Faz de Conta",
    descricao: "Brincadeira simbólica de mercado para explorar quantidade, listas, escolhas e linguagem social.",
    categoria: "Matematica",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "4 semanas",
    objetivos: ["Contar pequenas quantidades em contexto real.", "Criar listas com marcas e desenhos.", "Negociar papéis durante a brincadeira."],
    atividades: ["Montagem das bancas", "Lista de compras", "Moedas de brincadeira", "Classificar produtos", "Dia do mercado"],
    materiais: ["embalagens limpas", "etiquetas", "papel", "tampinhas", "cestas", "canetões"],
    codigos: ["EI02ET07", "EI02EF09", "EI02EO06", "EI02TS02"],
  },
  {
    titulo: "Culinária Afetiva",
    descricao: "Receitas simples e seguras para medir, misturar, conversar sobre memórias e compartilhar.",
    categoria: "Bem-estar",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "3 semanas",
    objetivos: ["Participar de preparo culinário seguro.", "Comparar medidas não convencionais.", "Valorizar histórias familiares ligadas à comida."],
    atividades: ["Receita de família", "Medidas com copos", "Misturas e aromas", "Livro de receitas", "Degustação coletiva"],
    materiais: ["copos medidores", "tigelas", "frutas", "colheres", "papel", "fotos"],
    codigos: ["EI02ET07", "EI02EO05", "EI02EF04", "EI02CG04"],
  },
  {
    titulo: "Animais do Entorno",
    descricao: "Projeto de pesquisa sobre animais próximos à escola com cuidado, classificação e desenho.",
    categoria: "Natureza",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "4 semanas",
    objetivos: ["Observar animais com respeito.", "Comparar características como patas, asas e sons.", "Produzir registros de pesquisa."],
    atividades: ["Passeio de observação", "Sons dos animais", "Cartaz de características", "Modelagem em massinha", "Roda de cuidado"],
    materiais: ["lupas", "livros", "massinha", "cartolina", "adesivos", "imagens"],
    codigos: ["EI02ET03", "EI02EF01", "EI02TS02", "EI02EO04"],
  },
  {
    titulo: "Música e Gestos do Maternal",
    descricao: "Canções com sequência de gestos para trabalhar memória, ritmo e coordenação.",
    categoria: "Música",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "3 semanas",
    objetivos: ["Memorizar pequenas sequências musicais.", "Coordenar gestos e ritmo.", "Criar variações para canções conhecidas."],
    atividades: ["Canção com comandos", "Eco rítmico", "Instrumentos de sucata", "Coreografia simples", "Apresentação para outra turma"],
    materiais: ["potes", "sementes", "fitas", "caixa de som", "cartazes", "tecidos"],
    codigos: ["EI02TS03", "EI02CG03", "EI02EF02", "EI02EO06"],
  },
  {
    titulo: "Mapas da Sala",
    descricao: "Exploração dos espaços da sala com mapas afetivos, trajetos e combinados visuais.",
    categoria: "Sociedade",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "3 semanas",
    objetivos: ["Reconhecer espaços e funções da sala.", "Representar trajetos por desenho.", "Participar da organização coletiva."],
    atividades: ["Passeio pelos cantos", "Foto de cada espaço", "Caminhos no chão", "Mapa coletivo", "Combinados do cuidado"],
    materiais: ["fotos", "fita crepe", "papel kraft", "canetões", "adesivos", "pranchetas"],
    codigos: ["EI02EO01", "EI02ET04", "EI02EF01", "EI02TS02"],
  },
  {
    titulo: "Caixas e Construções",
    descricao: "Construção com caixas para investigar tamanho, equilíbrio, colaboração e planejamento.",
    categoria: "Criatividade",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "4 semanas",
    objetivos: ["Construir estruturas com materiais reaproveitados.", "Testar equilíbrio e encaixes.", "Planejar em pequenos grupos."],
    atividades: ["Explorar caixas", "Torres e pontes", "Casas imaginadas", "Pintura das construções", "Cidade de caixas"],
    materiais: ["caixas", "fita adesiva", "tinta", "pincéis", "papelão", "rolos"],
    codigos: ["EI02ET05", "EI02TS02", "EI02EO06", "EI02CG05"],
  },
  {
    titulo: "Chuva, Sol e Tempo",
    descricao: "Observação do clima diário com calendário visual, experiências e linguagem científica inicial.",
    categoria: "Natureza",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "4 semanas",
    objetivos: ["Observar mudanças no tempo.", "Usar símbolos para registrar clima.", "Relacionar vestimentas e cuidados ao clima."],
    atividades: ["Janela do tempo", "Calendário climático", "Som da chuva", "Roupas para cada dia", "Gráfico da semana"],
    materiais: ["cartolina", "símbolos", "potes", "algodão", "adesivos", "canetões"],
    codigos: ["EI02ET02", "EI02ET07", "EI02EF01", "EI02EO04"],
  },
  {
    titulo: "Nomes e Pertencimento",
    descricao: "Investigação dos nomes da turma com fotos, chamadas afetivas e primeiras marcas escritas.",
    categoria: "Linguagem",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "3 semanas",
    objetivos: ["Reconhecer o próprio nome em contextos significativos.", "Valorizar identidades da turma.", "Produzir marcas gráficas com intenção."],
    atividades: ["Chamada com fotos", "Caça ao nome", "Letras móveis", "Meu retrato", "Mural dos nomes"],
    materiais: ["fotos", "cartões", "letras móveis", "espelhos", "papel", "canetões"],
    codigos: ["EI02EF09", "EI02EO05", "EI02TS02", "EI02CG05"],
  },
  {
    titulo: "Brincadeiras de Roda",
    descricao: "Pesquisa de cantigas e jogos coletivos para fortalecer cultura oral, ritmo e convivência.",
    categoria: "Música",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "3 semanas",
    objetivos: ["Participar de rodas cantadas.", "Respeitar turnos e combinados.", "Conhecer brincadeiras tradicionais."],
    atividades: ["Roda conhecida", "Cantiga da família", "Gestos combinados", "Registro da música", "Roda com convidados"],
    materiais: ["caixa de som", "cartazes", "fitas", "instrumentos simples", "papel", "fotos"],
    codigos: ["EI02TS03", "EI02EO06", "EI02EF02", "EI02CG03"],
  },
  {
    titulo: "Reciclar para Brincar",
    descricao: "Transformação de sucatas limpas em brinquedos, instrumentos e jogos para a sala.",
    categoria: "Sociedade",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "4 semanas",
    objetivos: ["Reconhecer materiais que podem ser reutilizados.", "Criar brinquedos com sucata.", "Cuidar do espaço coletivo."],
    atividades: ["Coleta de sucatas", "Separar materiais", "Brinquedo inventado", "Teste de uso", "Feira de brinquedos"],
    materiais: ["sucata limpa", "cola", "fita", "tinta", "barbante", "cartolina"],
    codigos: ["EI02EO01", "EI02ET05", "EI02TS02", "EI02CG05"],
  },
  {
    titulo: "Formas no Cotidiano",
    descricao: "Caça às formas na escola com classificação, construção e jogos de pareamento.",
    categoria: "Matematica",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "3 semanas",
    objetivos: ["Identificar formas em objetos reais.", "Classificar por semelhanças.", "Construir figuras com diferentes materiais."],
    atividades: ["Caça ao círculo", "Mesa de formas", "Carimbo geométrico", "Construção com palitos", "Jogo de pareamento"],
    materiais: ["blocos", "palitos", "massinha", "carimbos", "cartolina", "adesivos"],
    codigos: ["EI02ET05", "EI02ET07", "EI02TS02", "EI02EF01"],
  },
  {
    titulo: "Jardim dos Pequenos Cientistas",
    descricao: "Experimentos simples de mistura, flutuação e observação para desenvolver hipóteses.",
    categoria: "Natureza",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Levantar hipóteses antes de experimentar.", "Registrar resultados com desenho e fala.", "Comparar materiais e transformações."],
    atividades: ["Mistura que muda de cor", "Afunda ou flutua", "Roda de hipóteses", "Diário ilustrado", "Mostra científica"],
    materiais: ["copos transparentes", "água", "corante", "objetos variados", "papel", "lupas"],
    codigos: ["EI03ET02", "EI03ET03", "EI03EF01", "EI03TS02"],
  },
  {
    titulo: "Matemática do Cotidiano no Jardim",
    descricao: "Situações reais de contagem, gráficos, medidas e comparação a partir da rotina da turma.",
    categoria: "Matematica",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Resolver problemas de contagem da rotina.", "Construir gráficos simples.", "Comparar medidas não convencionais."],
    atividades: ["Gráfico do lanche", "Medir com passos", "Calendário de ajudantes", "Desafio dos blocos", "Painel de números"],
    materiais: ["blocos", "cartolina", "etiquetas", "barbante", "canetões", "adesivos"],
    codigos: ["EI03ET07", "EI03ET08", "EI03EF01", "EI03EO03"],
  },
  {
    titulo: "Ateliê Criativo do Jardim",
    descricao: "Ateliê com técnicas variadas para experimentar materiais, autoria e exposição.",
    categoria: "Arte",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Experimentar técnicas e suportes diversos.", "Planejar uma produção autoral.", "Apreciar e comentar obras da turma."],
    atividades: ["Pintura com elementos naturais", "Escultura com recicláveis", "Colagem de texturas", "Curadoria das obras", "Galeria da turma"],
    materiais: ["tinta", "pincéis", "sucata", "cola", "papéis variados", "argila"],
    codigos: ["EI03TS02", "EI03TS03", "EI03EO04", "EI03EF01"],
  },
  {
    titulo: "Corpo em Circuito",
    descricao: "Percurso motor com planejamento, combinados de segurança e registro de conquistas.",
    categoria: "Corpo",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "3 semanas",
    objetivos: ["Planejar movimentos em sequência.", "Avaliar estratégias corporais.", "Cooperar para cumprir desafios."],
    atividades: ["Desenhar o circuito", "Saltar e equilibrar", "Arremesso ao alvo", "Circuito cooperativo", "Mapa das conquistas"],
    materiais: ["cones", "cordas", "bolas", "arcos", "cartolina", "adesivos"],
    codigos: ["EI03CG02", "EI03CG03", "EI03EO03", "EI03EF01"],
  },
  {
    titulo: "Pequenos Autores",
    descricao: "Criação de histórias coletivas com personagens, cenários, ditado ao professor e ilustração.",
    categoria: "Linguagem",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Criar narrativas com sequência lógica.", "Ditar textos para registro adulto.", "Ilustrar cenas com intenção comunicativa."],
    atividades: ["Banco de personagens", "Cenário coletivo", "Ditado da história", "Oficina de ilustração", "Lançamento do livro"],
    materiais: ["cartões", "papel", "canetões", "livros", "fantoches", "grampeador"],
    codigos: ["EI03EF04", "EI03EF05", "EI03TS02", "EI03EO04"],
  },
  {
    titulo: "Feira das Descobertas",
    descricao: "Projeto investigativo curto em que grupos escolhem perguntas e apresentam descobertas.",
    categoria: "Natureza",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "5 semanas",
    objetivos: ["Formular perguntas investigativas.", "Organizar resultados em cartazes.", "Apresentar descobertas para visitantes."],
    atividades: ["Perguntas da turma", "Grupos de pesquisa", "Experimento escolhido", "Cartaz científico", "Feira aberta"],
    materiais: ["cartolina", "lupas", "potes", "livros", "canetões", "etiquetas"],
    codigos: ["EI03ET03", "EI03EF01", "EI03EO03", "EI03TS02"],
  },
  {
    titulo: "Moradia e Cidade",
    descricao: "Investigação sobre casas, ruas e serviços da comunidade com maquete colaborativa.",
    categoria: "Sociedade",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Reconhecer diferentes moradias e espaços públicos.", "Representar trajetos e lugares.", "Valorizar trabalhadores da comunidade."],
    atividades: ["Minha casa por desenho", "Passeio pelo entorno", "Serviços da cidade", "Maquete colaborativa", "Roda com convidado"],
    materiais: ["caixas", "papelão", "tinta", "fotos", "mapas", "bonecos"],
    codigos: ["EI03EO06", "EI03ET04", "EI03EF01", "EI03TS02"],
  },
  {
    titulo: "Plantas que Contam Histórias",
    descricao: "Pesquisa de plantas da escola com observação, desenho científico e histórias inventadas.",
    categoria: "Natureza",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Observar partes das plantas.", "Produzir desenhos de observação.", "Criar narrativas a partir da natureza."],
    atividades: ["Mapa das plantas", "Folhas em detalhe", "Desenho científico", "História da árvore", "Livro botânico"],
    materiais: ["lupas", "pranchetas", "lápis de cor", "folhas", "papel", "livros"],
    codigos: ["EI03ET03", "EI03EF05", "EI03TS02", "EI03EO04"],
  },
  {
    titulo: "Trânsito e Caminhos Seguros",
    descricao: "Exploração de trajetos, placas e cuidados de circulação dentro e fora da escola.",
    categoria: "Sociedade",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "3 semanas",
    objetivos: ["Reconhecer sinais e combinados de circulação.", "Planejar trajetos seguros.", "Participar de simulações com respeito ao grupo."],
    atividades: ["Placas da escola", "Mapa do trajeto", "Semáforo corporal", "Cidade no chão", "Campanha de cuidado"],
    materiais: ["fita crepe", "cartolina", "cones", "papel colorido", "carrinhos", "coletes"],
    codigos: ["EI03EO06", "EI03CG02", "EI03ET04", "EI03EF01"],
  },
  {
    titulo: "Brinquedos Inventados",
    descricao: "Criação de brinquedos com materiais simples, teste de regras e melhorias.",
    categoria: "Criatividade",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Planejar e construir brinquedos.", "Testar funcionamento e regras.", "Ajustar projetos a partir da experiência."],
    atividades: ["Desenho da ideia", "Construção com sucata", "Teste com colegas", "Melhorias do protótipo", "Dia dos brinquedos"],
    materiais: ["sucata", "papelão", "elásticos", "barbante", "cola", "tinta"],
    codigos: ["EI03ET05", "EI03TS02", "EI03EO03", "EI03EF01"],
  },
  {
    titulo: "Emoções em Cores",
    descricao: "Percurso socioemocional com histórias, expressões, cores e combinados de cuidado.",
    categoria: "Bem-estar",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "3 semanas",
    objetivos: ["Nomear emoções em situações cotidianas.", "Expressar sentimentos por arte e fala.", "Construir estratégias de acolhimento."],
    atividades: ["História das emoções", "Roda do termômetro", "Pintura emocional", "Cartões de cuidado", "Cantinho da calma"],
    materiais: ["livros", "cartões", "tintas", "espelhos", "almofadas", "potes sensoriais"],
    codigos: ["EI03EO04", "EI03EO05", "EI03TS02", "EI03EF01"],
  },
  {
    titulo: "Músicas do Mundo",
    descricao: "Escuta e criação musical com ritmos de diferentes culturas e instrumentos de sala.",
    categoria: "Música",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Apreciar ritmos variados.", "Criar acompanhamentos com instrumentos simples.", "Respeitar manifestações culturais diferentes."],
    atividades: ["Mapa dos sons", "Ritmo com corpo", "Instrumentos de sucata", "Composição da turma", "Roda musical"],
    materiais: ["mapa", "caixa de som", "potes", "sementes", "tambores", "fitas"],
    codigos: ["EI03TS03", "EI03EO06", "EI03CG03", "EI03EF01"],
  },
  {
    titulo: "Sombra, Luz e Medo",
    descricao: "Investigação artística para transformar sombras em brincadeira, narrativa e expressão.",
    categoria: "Arte",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "3 semanas",
    objetivos: ["Investigar fontes de luz e sombra.", "Criar personagens por silhueta.", "Narrar histórias com teatro de sombras."],
    atividades: ["Laboratório de lanternas", "Silhuetas no papel", "Personagens de sombra", "Roteiro coletivo", "Teatro para a turma"],
    materiais: ["lanternas", "cartolina preta", "palitos", "papel vegetal", "fita", "tecido branco"],
    codigos: ["EI03ET02", "EI03TS02", "EI03EF04", "EI03EO03"],
  },
  {
    titulo: "Medidas na Cozinha",
    descricao: "Receitas e experimentos para comparar peso, volume, tempo e sequência de preparo.",
    categoria: "Matematica",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Usar medidas não convencionais e convencionais simples.", "Organizar sequência de preparo.", "Registrar comparações em tabelas."],
    atividades: ["Receita ilustrada", "Copos e colheres", "Tempo de mistura", "Tabela de preferências", "Lanche compartilhado"],
    materiais: ["copos", "colheres", "tigelas", "ingredientes", "cartolina", "relógio"],
    codigos: ["EI03ET07", "EI03ET08", "EI03EF01", "EI03EO03"],
  },
  {
    titulo: "Água que Vai e Volta",
    descricao: "Pesquisa sobre usos da água, economia, ciclo simplificado e experiências de evaporação.",
    categoria: "Natureza",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Observar usos e desperdícios de água.", "Compreender transformações simples.", "Criar campanha de cuidado."],
    atividades: ["Mapa dos usos da água", "Filtro experimental", "Evaporação no sol", "Cartazes de economia", "Dia do cuidado"],
    materiais: ["potes", "areia", "pedras", "filtro", "cartolina", "adesivos"],
    codigos: ["EI03ET03", "EI03EO06", "EI03EF01", "EI03TS02"],
  },
  {
    titulo: "Cultura Popular em Festa",
    descricao: "Pesquisa de danças, comidas, músicas e brincadeiras tradicionais com respeito cultural.",
    categoria: "Sociedade",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Conhecer manifestações culturais brasileiras.", "Participar de danças e brincadeiras tradicionais.", "Valorizar relatos das famílias."],
    atividades: ["Pesquisa com famílias", "Brincadeiras tradicionais", "Oficina de adereços", "Culinária de festa", "Celebração cultural"],
    materiais: ["fotos", "tecidos", "papel colorido", "música", "ingredientes", "cartazes"],
    codigos: ["EI03EO06", "EI03TS03", "EI03CG03", "EI03EF01"],
  },
  {
    titulo: "Laboratório de Escrita da Pré-escola",
    descricao: "Sequência de escrita significativa com listas, bilhetes, nomes e produção coletiva.",
    categoria: "Linguagem",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "5 semanas",
    objetivos: ["Produzir escritas com função social.", "Comparar letras e sons em nomes e palavras.", "Revisar textos coletivamente."],
    atividades: ["Lista da rotina", "Bilhete para famílias", "Oficina do nome completo", "Jornal da sala", "Sarau de leitura"],
    materiais: ["alfabeto móvel", "papel", "envelopes", "canetões", "livros", "pranchetas"],
    codigos: ["EI03EF07", "EI03EF09", "EI03EO04", "EI03TS02"],
  },
  {
    titulo: "Feira de Ciências da Pré-escola",
    descricao: "Investigação com germinação, registros em tabela e apresentação científica para visitantes.",
    categoria: "Natureza",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "6 semanas",
    objetivos: ["Planejar investigação com etapas.", "Registrar dados em tabela.", "Apresentar procedimentos e conclusões."],
    atividades: ["Pergunta investigativa", "Desafio da germinação", "Registro em tabela", "Treino de apresentação", "Feira de ciências"],
    materiais: ["sementes", "algodão", "potes", "tabelas", "cartolina", "lupas"],
    codigos: ["EI03ET03", "EI03ET08", "EI03EF01", "EI03EO03"],
  },
  {
    titulo: "Nossa Cidade e Comunidade",
    descricao: "Pesquisa sobre bairro, profissões, espaços públicos e pertencimento com maquete final.",
    categoria: "Sociedade",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "5 semanas",
    objetivos: ["Reconhecer serviços e pessoas da comunidade.", "Representar lugares por mapa e maquete.", "Valorizar diferentes trabalhos."],
    atividades: ["Mapa afetivo do bairro", "Entrevista com funcionárias", "Roteiro de passeio", "Maquete da comunidade", "Apresentação guiada"],
    materiais: ["mapas", "caixas", "fotos", "microfone de brinquedo", "cartolina", "tinta"],
    codigos: ["EI03EO06", "EI03EF01", "EI03ET04", "EI03TS02"],
  },
  {
    titulo: "Horta Pedagógica Integrada",
    descricao: "Projeto de plantio, medidas, cuidados e receitas com acompanhamento semanal.",
    categoria: "Natureza",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "8 semanas",
    objetivos: ["Organizar rotina de cuidado da horta.", "Medir crescimento e registrar mudanças.", "Relacionar colheita e alimentação saudável."],
    atividades: ["Preparação dos canteiros", "Agenda de cuidados", "Medida das plantas", "Receita da colheita", "Livro da horta"],
    materiais: ["terra", "sementes", "regadores", "régua", "cartolina", "ingredientes"],
    codigos: ["EI03ET03", "EI03ET08", "EI03EO03", "EI03EF01"],
  },
  {
    titulo: "Brincadeiras do Brasil",
    descricao: "Pesquisa e prática de brincadeiras regionais com regras, mapas e livro coletivo.",
    categoria: "Corpo",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "4 semanas",
    objetivos: ["Conhecer brincadeiras de diferentes regiões.", "Registrar regras por desenho e escrita.", "Cooperar em jogos coletivos."],
    atividades: ["Mapa das brincadeiras", "Circuito de amarelinha", "Cantigas com roda", "Livro das regras", "Festival de brincadeiras"],
    materiais: ["mapa", "giz", "corda", "cartolina", "fotos", "canetões"],
    codigos: ["EI03CG03", "EI03EO06", "EI03EF01", "EI03TS02"],
  },
  {
    titulo: "Jornal Mirim",
    descricao: "Produção de jornal da turma com entrevistas, notícias, fotos e revisão coletiva.",
    categoria: "Linguagem",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "5 semanas",
    objetivos: ["Diferenciar notícia, entrevista e legenda.", "Produzir textos coletivos.", "Revisar e publicar para uma audiência real."],
    atividades: ["Pauta da semana", "Entrevista da escola", "Foto e legenda", "Edição coletiva", "Distribuição do jornal"],
    materiais: ["papel", "câmera", "microfone de brinquedo", "computador", "canetões", "pranchetas"],
    codigos: ["EI03EF07", "EI03EF09", "EI03EO04", "EI03TS02"],
  },
  {
    titulo: "Museu da Turma",
    descricao: "Curadoria de objetos importantes para contar memórias, preferências e histórias pessoais.",
    categoria: "Sociedade",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "4 semanas",
    objetivos: ["Selecionar objetos com significado.", "Narrar memórias e preferências.", "Organizar exposição com legendas."],
    atividades: ["Objeto de memória", "Etiqueta de museu", "Organização por temas", "Visita mediada", "Livro de visitantes"],
    materiais: ["objetos pessoais", "etiquetas", "mesas", "papel", "canetas", "fotos"],
    codigos: ["EI03EO05", "EI03EF01", "EI03TS02", "EI03ET05"],
  },
  {
    titulo: "Matemática nos Jogos",
    descricao: "Jogos de tabuleiro, dados e trilhas para resolver problemas de contagem e estratégia.",
    categoria: "Matematica",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "4 semanas",
    objetivos: ["Contar pontos e casas em jogos.", "Comparar resultados.", "Criar regras de jogo com clareza."],
    atividades: ["Trilha gigante", "Dados e pontuação", "Dominó da turma", "Criar um jogo", "Torneio cooperativo"],
    materiais: ["dados", "tampinhas", "cartolina", "peões", "dominó", "adesivos"],
    codigos: ["EI03ET07", "EI03ET08", "EI03EO03", "EI03EF01"],
  },
  {
    titulo: "Cartas para Famílias",
    descricao: "Escrita de cartas, convites e envelopes para comunicar descobertas da turma.",
    categoria: "Linguagem",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "3 semanas",
    objetivos: ["Reconhecer carta e convite como gêneros sociais.", "Planejar mensagem para destinatário.", "Participar de revisão coletiva."],
    atividades: ["Ler cartas reais", "Planejar destinatário", "Escrever convite", "Envelope e selo", "Entrega especial"],
    materiais: ["cartas", "papel", "envelopes", "selos fictícios", "canetões", "adesivos"],
    codigos: ["EI03EF07", "EI03EF09", "EI03EO04", "EI03TS02"],
  },
  {
    titulo: "Robôs Recicláveis",
    descricao: "Construção de robôs com sucata para explorar partes, funções, medidas e apresentação oral.",
    categoria: "Criatividade",
    faixaEtaria: "Pré II (6-7 anos)",
    duracao: "5 semanas",
    objetivos: ["Planejar protótipo com desenho.", "Construir usando materiais reaproveitados.", "Explicar funções imaginadas para o robô."],
    atividades: ["Desenho do protótipo", "Escolha de peças", "Montagem do robô", "Ficha técnica", "Exposição tecnológica"],
    materiais: ["sucata", "papelão", "tampinhas", "cola quente supervisionada", "tinta", "etiquetas"],
    codigos: ["EI03ET05", "EI03TS02", "EI03EF01", "EI03EO03"],
  },
  {
    titulo: "Corpo, Saúde e Movimento",
    descricao: "Projeto sobre hábitos saudáveis, movimento, respiração e autocuidado.",
    categoria: "Bem-estar",
    faixaEtaria: "Pré II (6-7 anos)",
    duracao: "4 semanas",
    objetivos: ["Reconhecer hábitos de cuidado com o corpo.", "Relacionar movimento e bem-estar.", "Criar combinados de saúde para a turma."],
    atividades: ["Mapa do corpo", "Circuito saudável", "Respiração guiada", "Prato colorido", "Guia de autocuidado"],
    materiais: ["cartazes", "arcos", "bolas", "imagens de alimentos", "espelhos", "adesivos"],
    codigos: ["EI03CG04", "EI03EO05", "EI03EF01", "EI03ET07"],
  },
  {
    titulo: "Histórias em Quadrinhos",
    descricao: "Criação de HQs com personagens, balões de fala, sequência e revisão.",
    categoria: "Linguagem",
    faixaEtaria: "Pré II (6-7 anos)",
    duracao: "4 semanas",
    objetivos: ["Compreender sequência narrativa em quadrinhos.", "Usar balões e legendas.", "Produzir HQ autoral ou em dupla."],
    atividades: ["Ler tirinhas", "Criar personagem", "Roteiro em cenas", "Desenho dos quadros", "Banca de HQs"],
    materiais: ["tirinhas", "papel sulfite", "lápis", "canetinhas", "réguas", "grampeador"],
    codigos: ["EI03EF04", "EI03EF09", "EI03TS02", "EI03EO03"],
  },
  {
    titulo: "Pequenos Empreendedores",
    descricao: "Simulação de feira com produtos da turma, preços simbólicos e decisões coletivas.",
    categoria: "Matematica",
    faixaEtaria: "Pré II (6-7 anos)",
    duracao: "4 semanas",
    objetivos: ["Usar números em situações de compra e venda simulada.", "Planejar produtos e quantidades.", "Registrar escolhas e resultados."],
    atividades: ["Escolha dos produtos", "Tabela de preços", "Produção das etiquetas", "Feira simbólica", "Balanço coletivo"],
    materiais: ["etiquetas", "tampinhas", "cartolina", "produtos simbólicos", "cestas", "calculadora"],
    codigos: ["EI03ET07", "EI03ET08", "EI03EO03", "EI03EF01"],
  },
  {
    titulo: "Mapas e Tesouros",
    descricao: "Criação de mapas, pistas e caça ao tesouro para explorar orientação espacial.",
    categoria: "Matematica",
    faixaEtaria: "Pré II (6-7 anos)",
    duracao: "3 semanas",
    objetivos: ["Representar trajetos e posições.", "Interpretar pistas espaciais.", "Cooperar para resolver desafios."],
    atividades: ["Mapa da sala", "Símbolos e legendas", "Pistas em sequência", "Caça ao tesouro", "Criar desafio para outra turma"],
    materiais: ["papel kraft", "adesivos", "fita crepe", "caixas", "cartões", "canetões"],
    codigos: ["EI03ET04", "EI03ET07", "EI03EO03", "EI03EF01"],
  },
  {
    titulo: "Astronomia para Crianças",
    descricao: "Investigação sobre céu, lua, estrelas e planetas com modelos, observação e linguagem poética.",
    categoria: "Natureza",
    faixaEtaria: "Pré II (6-7 anos)",
    duracao: "5 semanas",
    objetivos: ["Levantar perguntas sobre o céu.", "Criar modelos simples de astros.", "Relacionar observações e narrativas."],
    atividades: ["Perguntas sobre o céu", "Diário da lua", "Sistema solar em escala livre", "Histórias de estrelas", "Planetário da sala"],
    materiais: ["bolas de isopor", "tinta", "cartolina preta", "lanternas", "livros", "barbante"],
    codigos: ["EI03ET03", "EI03EF05", "EI03TS02", "EI03EO04"],
  },
  {
    titulo: "Direitos das Crianças",
    descricao: "Projeto de escuta, histórias e cartazes para conversar sobre cuidado, respeito e participação.",
    categoria: "Sociedade",
    faixaEtaria: "Pré II (6-7 anos)",
    duracao: "4 semanas",
    objetivos: ["Reconhecer direitos em linguagem acessível.", "Expressar opiniões e necessidades.", "Construir combinados de respeito."],
    atividades: ["História sobre cuidado", "Roda de opiniões", "Cartazes dos direitos", "Combinados ilustrados", "Assembleia da turma"],
    materiais: ["livros", "cartolina", "canetões", "fotos", "adesivos", "microfone de brinquedo"],
    codigos: ["EI03EO01", "EI03EO06", "EI03EF01", "EI03TS02"],
  },
  {
    titulo: "Acolhimento e Descanso dos Bebês",
    descricao: "Percurso de acolhimento com objetos de vínculo, música suave, luz natural e rituais de descanso respeitosos.",
    categoria: "Bem-estar",
    faixaEtaria: "Berçário (0-1 ano)",
    duracao: "2 semanas",
    objetivos: ["Reconhecer sinais da rotina de acolhimento.", "Fortalecer vínculos com adultos de referência.", "Expressar conforto e desconforto por gestos, sons e movimentos."],
    atividades: ["Cesto de objetos de vínculo", "Canção de chegada", "Luzes suaves e tecidos", "Ritual de descanso", "Painel da rotina acolhedora"],
    materiais: ["tecidos macios", "objetos familiares", "almofadas", "caixa de som", "fotografias", "móbile"],
    codigos: ["EI01EO01", "EI01EO02", "EI01CG01", "EI01EF01"],
  },
  {
    titulo: "Dança dos Animais",
    descricao: "Brincadeiras de imitação com gestos, deslocamentos e sons de animais para ampliar expressão e repertório corporal.",
    categoria: "Corpo",
    faixaEtaria: "Berçário (1-2 anos)",
    duracao: "3 semanas",
    objetivos: ["Imitar movimentos de animais conhecidos.", "Experimentar ritmos e deslocamentos variados.", "Interagir com colegas em brincadeiras corporais."],
    atividades: ["Quem anda assim", "Rastejar e saltar", "Sons e gestos", "Trilha dos animais", "Baile do quintal"],
    materiais: ["figuras de animais", "tecidos", "arcos", "almofadas", "caixa de som", "pegadas de papel"],
    codigos: ["EI01CG03", "EI01TS03", "EI01EO03", "EI01EF05"],
  },
  {
    titulo: "Meu Corpo e Meus Cuidados",
    descricao: "Projeto sobre higiene, alimentação, descanso e reconhecimento do corpo por meio de brincadeiras e rotinas significativas.",
    categoria: "Bem-estar",
    faixaEtaria: "Maternal I (2-3 anos)",
    duracao: "3 semanas",
    objetivos: ["Reconhecer partes do próprio corpo.", "Participar de ações de higiene com autonomia progressiva.", "Comunicar necessidades de cuidado e bem-estar."],
    atividades: ["Espelho e corpo", "Mãos bem cuidadas", "Boneco da rotina", "Respirar e descansar", "Livro dos cuidados"],
    materiais: ["espelhos", "bonecos", "toalhas", "figuras", "papel kraft", "lápis de cor"],
    codigos: ["EI02CG04", "EI02EO02", "EI02EF01", "EI02TS02"],
  },
  {
    titulo: "Insetos do Jardim",
    descricao: "Observação cuidadosa de pequenos animais do jardim, seus movimentos, abrigos e importância para o ambiente.",
    categoria: "Natureza",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "4 semanas",
    objetivos: ["Observar insetos sem retirá-los do ambiente.", "Comparar formas, cores e movimentos.", "Desenvolver atitudes de cuidado com seres vivos."],
    atividades: ["Passeio de observação", "Hotel de insetos simbólico", "Asas e movimentos", "Desenho com lupa", "Guia ilustrado da turma"],
    materiais: ["lupas", "pranchetas", "livros", "gravetos", "papel", "lápis de cor"],
    codigos: ["EI02ET03", "EI02EO01", "EI02CG03", "EI02TS02"],
  },
  {
    titulo: "Famílias e Afetos",
    descricao: "Projeto de identidade que acolhe diferentes configurações familiares por meio de histórias, fotografias e narrativas das crianças.",
    categoria: "Sociedade",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "3 semanas",
    objetivos: ["Reconhecer diferentes formas de organização familiar.", "Narrar experiências de cuidado e convivência.", "Valorizar vínculos e respeitar diferenças."],
    atividades: ["Quem cuida de mim", "Histórias de famílias", "Casa dos afetos", "Retrato com colagem", "Galeria das famílias"],
    materiais: ["fotografias", "livros", "papéis coloridos", "tecidos", "cola", "molduras de papelão"],
    codigos: ["EI02EO01", "EI02EO05", "EI02EF01", "EI02TS02"],
  },
  {
    titulo: "Barro, Terra e Argila",
    descricao: "Ateliê sensorial e artístico com argila, terra e elementos naturais para investigar marcas, volumes e transformações.",
    categoria: "Arte",
    faixaEtaria: "Maternal II (3-4 anos)",
    duracao: "3 semanas",
    objetivos: ["Explorar propriedades de materiais naturais.", "Criar formas tridimensionais com intenção.", "Perceber mudanças provocadas por água, pressão e secagem."],
    atividades: ["Terra seca e molhada", "Marcas da natureza", "Pequenos recipientes", "Escultura coletiva", "Exposição tátil"],
    materiais: ["argila", "terra peneirada", "água", "folhas", "gravetos", "bases de madeira"],
    codigos: ["EI02TS02", "EI02ET02", "EI02CG05", "EI02EO03"],
  },
  {
    titulo: "Oceano e Vida Marinha",
    descricao: "Investigação sobre animais marinhos, ambientes costeiros e atitudes cotidianas de cuidado com as águas.",
    categoria: "Natureza",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "5 semanas",
    objetivos: ["Conhecer diferentes animais e ambientes marinhos.", "Relacionar resíduos e preservação das águas.", "Comunicar descobertas por modelos, desenhos e narrativas."],
    atividades: ["Mapa do oceano", "Animais da superfície e do fundo", "Experiência de flutuação", "Praia sem lixo", "Museu do mar"],
    materiais: ["mapas", "conchas", "potes", "miniaturas", "papelão", "tintas"],
    codigos: ["EI03ET03", "EI03EO06", "EI03EF01", "EI03TS02"],
  },
  {
    titulo: "Abelhas e Polinização",
    descricao: "Projeto sobre flores, abelhas e polinização com observação segura, modelos e plantio de espécies atrativas.",
    categoria: "Natureza",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Compreender de forma inicial a relação entre flores e polinizadores.", "Observar abelhas mantendo distância segura.", "Participar do cuidado de plantas do jardim."],
    atividades: ["Flores que visitamos", "Corpo da abelha", "Pólen em movimento", "Plantio para polinizadores", "Campanha de proteção"],
    materiais: ["flores", "lupas", "pincéis", "pó colorido", "sementes", "cartolina"],
    codigos: ["EI03ET03", "EI03EO06", "EI03TS02", "EI03EF01"],
  },
  {
    titulo: "Guardiões do Planeta",
    descricao: "Percurso de sustentabilidade com redução de resíduos, reaproveitamento, cuidado com água e ações possíveis na escola.",
    categoria: "Natureza",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "5 semanas",
    objetivos: ["Identificar atitudes de cuidado ambiental na rotina.", "Reduzir desperdícios em ações concretas.", "Mobilizar a comunidade escolar com linguagem infantil."],
    atividades: ["Mapa dos resíduos", "Desafio sem desperdício", "Reuso criativo", "Cuidado com a água", "Pacto da turma"],
    materiais: ["embalagens limpas", "caixas", "baldes", "cartolina", "adesivos", "balança simples"],
    codigos: ["EI03ET03", "EI03EO06", "EI03EF01", "EI03TS02"],
  },
  {
    titulo: "Pontes e Estruturas",
    descricao: "Desafios de construção com blocos e materiais reutilizáveis para investigar equilíbrio, resistência e planejamento coletivo.",
    categoria: "Criatividade",
    faixaEtaria: "Jardim I (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Planejar construções a partir de desenhos.", "Testar equilíbrio e resistência de estruturas.", "Revisar soluções em colaboração com colegas."],
    atividades: ["Pontes que conhecemos", "Desafio entre duas mesas", "Peso e resistência", "Ponte da turma", "Mostra de soluções"],
    materiais: ["blocos", "papelão", "rolos", "barbante", "palitos", "pesos leves"],
    codigos: ["EI03ET01", "EI03ET05", "EI03EO03", "EI03EF01"],
  },
  {
    titulo: "Povos Indígenas do Brasil Hoje",
    descricao: "Projeto de aproximação respeitosa com a diversidade dos povos indígenas contemporâneos por meio de literatura de autoria indígena, mapas e produções artísticas contextualizadas.",
    categoria: "Sociedade",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "5 semanas",
    objetivos: ["Reconhecer que existem muitos povos indígenas com modos de vida diversos.", "Apreciar narrativas e obras de autoria indígena.", "Evitar generalizações e valorizar conhecimentos contemporâneos."],
    atividades: ["Muitos povos, muitos lugares", "Leitura de autoria indígena", "Línguas e nomes", "Arte com contexto", "Mostra de aprendizagens"],
    materiais: ["livros de autoria indígena", "mapa do Brasil", "fotografias autorizadas", "papel", "tintas naturais", "argila"],
    codigos: ["EI03EO06", "EI03EF03", "EI03TS02", "EI03ET04"],
  },
  {
    titulo: "Histórias e Culturas Afro-Brasileiras",
    descricao: "Projeto de valorização da presença negra no Brasil com literatura, arte, música, memória e referências positivas do cotidiano.",
    categoria: "Sociedade",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "5 semanas",
    objetivos: ["Ampliar referências positivas de pessoas negras.", "Conhecer narrativas e expressões afro-brasileiras contextualizadas.", "Fortalecer respeito à diversidade étnico-racial."],
    atividades: ["Biblioteca de protagonismos", "Retratos e identidades", "Ritmos com contexto", "Memórias de família", "Galeria de referências"],
    materiais: ["literatura infantil", "fotografias", "espelhos", "tecidos", "instrumentos", "materiais de pintura"],
    codigos: ["EI03EO05", "EI03EO06", "EI03EF03", "EI03TS03"],
  },
  {
    titulo: "Estações do Ano e Mudanças",
    descricao: "Observação das transformações do clima, das plantas, das roupas e da rotina ao longo das estações.",
    categoria: "Natureza",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "6 semanas",
    objetivos: ["Observar mudanças no ambiente e no clima.", "Relacionar condições do tempo a escolhas da rotina.", "Organizar registros em sequência temporal."],
    atividades: ["Árvore das estações", "Diário do tempo", "Roupas e temperaturas", "Cores da paisagem", "Calendário de mudanças"],
    materiais: ["calendário", "fotografias", "folhas", "tecidos", "termômetro", "papel kraft"],
    codigos: ["EI03ET02", "EI03ET04", "EI03EF01", "EI03TS02"],
  },
  {
    titulo: "Teatro de Histórias",
    descricao: "Criação coletiva de cenas com personagens, cenários, expressão corporal e apresentação para uma audiência real.",
    categoria: "Linguagem",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Construir narrativas com começo, desenvolvimento e desfecho.", "Expressar personagens por voz, gesto e movimento.", "Cooperar na criação de cenas e cenários."],
    atividades: ["Escolha da história", "Laboratório de personagens", "Cenário coletivo", "Ensaios em pequenos grupos", "Apresentação da turma"],
    materiais: ["livros", "tecidos", "caixas", "fantoches", "papelão", "objetos sonoros"],
    codigos: ["EI03EF04", "EI03CG03", "EI03TS02", "EI03EO03"],
  },
  {
    titulo: "Fotografia: Olhares da Infância",
    descricao: "Projeto de observação e autoria com enquadramentos, detalhes, luz e curadoria de fotografias produzidas pelas crianças.",
    categoria: "Arte",
    faixaEtaria: "Jardim II (4-5 anos)",
    duracao: "4 semanas",
    objetivos: ["Observar o ambiente por diferentes pontos de vista.", "Produzir imagens com intenção comunicativa.", "Selecionar e comentar fotografias respeitando direitos de imagem."],
    atividades: ["Molduras de papel", "Caça aos detalhes", "Luz e sombra na foto", "Curadoria em duplas", "Exposição de olhares"],
    materiais: ["câmera ou tablet", "molduras de papel", "lanternas", "objetos", "impressões", "painel"],
    codigos: ["EI03TS02", "EI03EF01", "EI03ET04", "EI03EO03"],
  },
  {
    titulo: "Dinossauros e Fósseis",
    descricao: "Investigação sobre animais do passado, fósseis, tempo e evidências científicas com escavação simulada e registros.",
    categoria: "Natureza",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "5 semanas",
    objetivos: ["Diferenciar evidência científica e imaginação.", "Compreender que seres vivos habitaram a Terra em outros tempos.", "Registrar hipóteses e descobertas em linguagem infantil."],
    atividades: ["O que sabemos", "Escavação simulada", "Pegadas e medidas", "Linha do tempo visual", "Museu de fósseis"],
    materiais: ["réplicas de fósseis", "areia", "pincéis", "argila", "régua", "livros informativos"],
    codigos: ["EI03ET03", "EI03ET04", "EI03EF01", "EI03TS02"],
  },
  {
    titulo: "Acessibilidade e Jeitos de Participar",
    descricao: "Projeto sobre barreiras, recursos de acessibilidade e diferentes formas de brincar, comunicar e participar na escola.",
    categoria: "Sociedade",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "4 semanas",
    objetivos: ["Reconhecer que pessoas participam de maneiras diferentes.", "Identificar barreiras simples nos espaços e brincadeiras.", "Criar adaptações com respeito, sem simular deficiências."],
    atividades: ["Todos conseguem participar", "Mapa de barreiras", "Comunicar de outros jeitos", "Brinquedo acessível", "Guia de acolhimento"],
    materiais: ["livros", "pictogramas", "blocos", "tecidos", "papelão", "pranchas de comunicação"],
    codigos: ["EI03EO01", "EI03EO05", "EI03EO06", "EI03EF01"],
  },
  {
    titulo: "Sabores do Brasil",
    descricao: "Pesquisa culinária sobre frutas, preparos e memórias alimentares de diferentes regiões, respeitando alergias e culturas familiares.",
    categoria: "Cultura",
    faixaEtaria: "Pré I (5-6 anos)",
    duracao: "5 semanas",
    objetivos: ["Conhecer alimentos presentes em diferentes regiões brasileiras.", "Registrar receitas e preferências da turma.", "Valorizar memórias alimentares das famílias."],
    atividades: ["Mapa dos sabores", "Pesquisa com famílias", "Frutas brasileiras", "Receita ilustrada", "Caderno coletivo"],
    materiais: ["mapa", "frutas", "utensílios seguros", "fichas", "papel", "fotografias"],
    codigos: ["EI03EO06", "EI03ET07", "EI03EF07", "EI03TS02"],
  },
  {
    titulo: "Arquitetura das Brincadeiras",
    descricao: "Planejamento e construção de cabanas, percursos e espaços de faz de conta com análise de uso, estabilidade e cooperação.",
    categoria: "Criatividade",
    faixaEtaria: "Pré II (6-7 anos)",
    duracao: "5 semanas",
    objetivos: ["Representar ideias em plantas e desenhos simples.", "Construir espaços considerando estabilidade e função.", "Avaliar e melhorar projetos a partir do uso coletivo."],
    atividades: ["Espaços de brincar", "Planta da ideia", "Teste de materiais", "Construção coletiva", "Visita guiada"],
    materiais: ["caixas grandes", "tecidos", "pregadores", "barbante", "papel kraft", "trena"],
    codigos: ["EI03ET04", "EI03ET05", "EI03EO03", "EI03TS02"],
  },
  {
    titulo: "Pássaros da Nossa Região",
    descricao: "Observação ética de aves do entorno com escuta de cantos, desenho, pesquisa de hábitos e ações de cuidado.",
    categoria: "Natureza",
    faixaEtaria: "Pré II (6-7 anos)",
    duracao: "5 semanas",
    objetivos: ["Reconhecer aves frequentes no entorno da escola.", "Comparar bicos, penas, cantos e hábitos.", "Realizar observações sem capturar ou alimentar inadequadamente."],
    atividades: ["Escuta no pátio", "Guia de observação", "Bicos e alimentos", "Ninhos sem tocar", "Mapa das aves"],
    materiais: ["binóculos de brinquedo", "gravador", "livros", "pranchetas", "lápis", "mapa"],
    codigos: ["EI03ET03", "EI03EF01", "EI03TS02", "EI03EO06"],
  },
];

export const PROJECT_CATALOG: ProjectCatalogItem[] = PROJECT_BLUEPRINTS.map(buildProject);
